# Generated by Django 4.1.dev20211222104755 on 2021-12-29 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=220)),
                ('price_cents', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CommReq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_init', models.DateTimeField(auto_now=True)),
                ('date_mod', models.DateTimeField(auto_now_add=True, verbose_name='last modified')),
                ('user', models.EmailField(max_length=254)),
                ('commType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commissions.commtype')),
            ],
        ),
    ]
