# Generated by Django 4.1.dev20211222104755 on 2021-12-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commtype',
            old_name='price_cents',
            new_name='price',
        ),
        migrations.AddField(
            model_name='commreq',
            name='user_id',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
