# Generated by Django 4.1.dev20211222104755 on 2021-12-29 17:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_rename_price_cents_commtype_price_commreq_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='commreq',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commreq',
            name='date_accepted',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commtype',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
