# Generated by Django 4.1.dev20211222104755 on 2021-12-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0003_commreq_complete_commreq_date_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commreq',
            name='charnotes',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='commreq',
            name='comments',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='commreq',
            name='contact',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='commreq',
            name='file',
            field=models.FileField(null=True, upload_to='user/uploads/'),
        ),
        migrations.AlterField(
            model_name='commreq',
            name='date_accepted',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='commreq',
            name='date_mod',
            field=models.DateTimeField(verbose_name='last modified'),
        ),
        migrations.AlterField(
            model_name='commreq',
            name='user',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='commreq',
            name='user_id',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
